implement quiet option for wpget
git-svn-id: file:///Users/michaelkoepke/svn/semiologic/scripts/wp/trunk@958 6c9c31c4-cb3d-4424-af3d-876279169c7e

diff --git a/wpget b/wpget
--- a/wpget
+++ b/wpget
@@ -2,9 +2,36 @@
 #
 # WP/Sem Pro package regenerator
 # Author: Denis de Bernardy <http://www.mesoconcepts.com>
-# Version: 0.1
+# Version: 0.2
 # http://www.mesoconcepts.com/license/
 #
+
+# init args
+quiet=0
+
+# extract args
+while [ $# -gt 0 ];
+do
+	if [ $1 != ${1#-} ];
+	then
+		case $1
+		in
+			'--quiet' )
+				quiet=1
+				;;
+			* )
+				echo "Invalid option ($1)."
+				exit 1
+				;;
+		esac
+	else
+		echo "Invalid argument ($1)."
+		exit 1
+	fi
+	
+	shift
+done
+
 
 # fetch path
 if [ $USER = 'root' ];
@@ -140,7 +167,7 @@ fi
 
 
 # Repackage if necessary
-cmp ~/.wpget ~/.wpget.$dir 2> /dev/null
+cmp ~/.wpget ~/.wpget.$dir &> /dev/null
 
 if [ $? -eq 0 ];
 then
@@ -149,7 +176,10 @@ then
 fi
 
 
-echo "Repackaging $path/wordpress ..."
+if [ $quiet -eq 0 ];
+then
+	echo "Repackaging $path/wordpress ..."
+fi
 
 mkdir -p /tmp/$dir
 cd /tmp/$dir
