update wpget for sem pro users
git-svn-id: file:///Users/michaelkoepke/svn/semiologic/scripts/wp/trunk@2291 6c9c31c4-cb3d-4424-af3d-876279169c7e

diff --git a/wpget b/wpget
--- a/wpget
+++ b/wpget
@@ -1,13 +1,15 @@
 #!/bin/sh
 #
-# WP/Sem Pro package regenerator
+# WP/Sem Pro packager
 # Author: Denis de Bernardy <http://www.mesoconcepts.com>
-# Version: 0.6
+# Version: 0.7
 # http://www.mesoconcepts.com/license/
 #
 
 # init args
 quiet=0
+sem_pro=''
+sem_key=''
 
 # extract args
 while [ $# -gt 0 ];
@@ -16,9 +18,15 @@ do
 	then
 		case $1
 		in
+			'-k' )
+				shift
+				sem_key=$1
+				;;
+			
 			'--quiet' )
 				quiet=1
 				;;
+			
 			* )
 				echo "Invalid option ($1)."
 				exit 1
@@ -63,16 +71,21 @@ fi
 
 
 # inititialize
-wp_core="wordpress"
-wp_themes=
-wp_plugins="auto-thickbox archive-widgets sem-external-links sem-admin-menu sem-author-image sem-autolink-uri sem-dofollow sem-fancy-excerpt sem-frame-buster sem-opt-in-front link-widgets uploads-folder text-widgets xml-sitemaps"
-sem_themes="sem-reloaded"
-sem_plugins=
+core='sem-pro wordpress'
+wp_themes='p2'
+wp_plugins='auto-thickbox core-control sem-admin-menu sem-autolink-uri sem-author-image sem-external-links sem-dofollow sem-fancy-excerpt sem-frame-buster sem-opt-in-front sem-unfancy-quote uploads-folder wp-db-backup wp-hashcash xml-sitemaps'
+sem_themes=''
+sem_plugins=''
 
 
 cwd=$PWD
 
 dir=`uuidgen`
+
+if [ "$sem_key" = '' ];
+then
+	sem_key=`cat /etc/semiologic 2> /dev/null`
+fi
 
 touch ~/.wpget
 touch ~/.wpget.$dir
@@ -81,11 +94,27 @@ trap "cd $cwd; rm -Rf /tmp/$dir 2> /dev/null; rm -f ~/.wpget.$dir 2> /dev/null" 
 
 
 # wp_core
-for package in $wp_core;
+for package in $core;
 do
 	# debug
 	case $package
 	in
+		"sem-pro" )
+			if [ "$sem_key" = '' ];
+			then
+				continue
+			fi
+			service=https://api.semiologic.com/version/0.2/core/$sem_key
+			response=`curl -s --connect-timeout 3 -f $service`
+			sleep .2
+			sem_pro=`echo $response | cut -d , -f 3`
+			if [ "$sem_pro" != '' ];
+			then
+				echo $response >> ~/.wpget.$dir
+				break
+			fi
+			;;
+		
 		wordpress )
 			service=http://api.wordpress.org/core/version-check/1.3/
 			response=`curl -s --connect-timeout 3 -f $service`
@@ -96,7 +125,6 @@ do
 				echo "Err: $service returned an invalid response."
 				exit 1
 			fi
-	
 			echo "wordpress,`echo $response | cut -d ' ' -f 4`,`echo $response | cut -d ' ' -f 3`" >> ~/.wpget.$dir
 			;;
 		* )
@@ -117,7 +145,8 @@ done
 
 if [ "$args" != '' ];
 then
-	args=`echo '$send =' "array($args);" '$send['current_theme'] = (object) null; echo "themes=" . urlencode(serialize($send));'`
+	args=`echo '$send =' "array($args);" '$send["current_theme"] = (object) null; echo "themes=" . urlencode(serialize($send));'`
+	
 	args=`php -r "$args"`
 	
 	response=`curl -s --connect-timeout 3 -f $service -d "$args"`
@@ -133,36 +162,39 @@ then
 fi
 
 
-# wp_plugins
-args=
-service=http://api.wordpress.org/plugins/update-check/1.0/
-
-for package in $wp_plugins;
-do
-	args=`echo $args "'$package/$package.php' => array('Name' => '$package'), "`
-done
-
-if [ "$args" != '' ];
+if [ "$sem_pro" = '' ];
 then
-	args=`echo '$plugins =' "array($args);" '$send = (object) null; $send->plugins=$plugins; $send->active=array(); echo "plugins=" . urlencode(serialize($send));'`
-	args=`php -r "$args"`
+	# wp_plugins
+	args=
+	service=http://api.wordpress.org/plugins/update-check/1.0/
 	
-	response=`curl -s --connect-timeout 3 -f $service -d "$args"`
-	sleep .2
-			
-	if [ "$response" = '' ];
-	then
-		echo "Err: $service returned an invalid response."
-		exit 1
-	fi
-	
-	response=`echo '$plugins =' "unserialize('$response');" 'foreach ( $plugins as $plugin ) { echo preg_replace("|[^a-z0-9_-]|", "", $plugin->slug) . "," . preg_replace("|[^0-9\.]|", "", $plugin->new_version) . "," . preg_replace("|[^a-z0-9.:/_-]|", "", $plugin->package) . " "; }'`
-	response=`php -r "$response"`
-	
-	for details in $response;
+	for package in $wp_plugins;
 	do
-		echo $details >> ~/.wpget.$dir
+		args=`echo $args "'$package/$package.php' => array('Name' => '$package'), "`
 	done
+	
+	if [ "$args" != '' ];
+	then
+		args=`echo '$plugins =' "array($args);" '$send = (object) null; $send->plugins=$plugins; $send->active=array(); echo "plugins=" . urlencode(serialize($send));'`
+		args=`php -r "$args"`
+		
+		response=`curl -s --connect-timeout 3 -f $service -d "$args"`
+		sleep .2
+		
+		if [ "$response" = '' ];
+		then
+			echo "Err: $service returned an invalid response."
+			exit 1
+		fi
+		
+		response=`echo '$plugins =' "unserialize('$response');" 'foreach ( $plugins as $plugin ) { echo preg_replace("|[^a-z0-9_-]|", "", $plugin->slug) . "," . preg_replace("|[^0-9\.]|", "", $plugin->new_version) . "," . preg_replace("|[^a-z0-9.:/_-]|", "", $plugin->package) . " "; }'`
+		response=`php -r "$response"`
+
+		for details in $response;
+		do
+			echo $details >> ~/.wpget.$dir
+		done
+	fi
 fi
 
 
@@ -181,17 +213,30 @@ then
 	echo "Repackaging $path/wordpress ..."
 fi
 
+
 mkdir -p /tmp/$dir
 cd /tmp/$dir
 
 
 # wp_core
-for package in $wp_core;
+for package in $core;
 do
 	url=`cat ~/.wpget.$dir | grep $package, | cut -d , -f 3`
-	curl -s --connect-timeout 3 -f $url -o /tmp/$dir/wordpress.zip		|| exit 1
-	$cmd /tmp/$dir/wordpress.zip 1> /dev/null							|| exit 1
-	rm -f /tmp/$dir/wordpress.zip 2> /dev/null
+	if [ "$url" = '' ];
+	then
+		continue
+	fi
+	
+	if [ "$sem_pro" != '' ];
+	then
+		cookies=`curl -s --connect-timeout 3 -f https://api.semiologic.com/auth/0.1/$sem_key`
+		curl -s --connect-timeout 3 -b "$cookies" -f $url -o /tmp/$dir/$package.zip		|| exit 1
+	else
+		curl -s --connect-timeout 3 -f $url -o /tmp/$dir/$package.zip		|| exit 1
+	fi
+	
+	$cmd /tmp/$dir/$package.zip 1> /dev/null							|| exit 1
+	rm -f /tmp/$dir/$package.zip 2> /dev/null
 done
 
 
@@ -199,6 +244,10 @@ done
 for package in $wp_themes;
 do
 	url=`cat ~/.wpget.$dir | grep $package, | cut -d , -f 3`
+	if [ "$url" = '' ];
+	then
+		continue
+	fi
 	curl -s --connect-timeout 3 -f $url -o /tmp/$dir/$package.zip		|| exit 1
 	$cmd /tmp/$dir/$package.zip 1> /dev/null							|| exit 1
 	mv /tmp/$dir/$package /tmp/$dir/wordpress/wp-content/themes/$package 2> /dev/null
@@ -210,6 +259,10 @@ done
 for package in $wp_plugins;
 do
 	url=`cat ~/.wpget.$dir | grep $package, | cut -d , -f 3`
+	if [ "$url" = '' ];
+	then
+		continue
+	fi
 	curl -s --connect-timeout 3 -f $url -o /tmp/$dir/$package.zip		|| exit 1
 	$cmd /tmp/$dir/$package.zip 1> /dev/null							|| exit 1
 	mv /tmp/$dir/$package /tmp/$dir/wordpress/wp-content/plugins/$package 2> /dev/null
